### ISSUE TITLE
for  ext.kotlin_version = '1.9.22'  this error

### ISSUE THREAD

**Issue by naveenpardeep** [Biscozum/mobkit_calendar#68]
A problem occurred configuring project ':mobkit_calendar'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

**Comment by burakhang** [comment]
Hi, we tried to catch the error you mentioned by changing our kotlin version to "1.9.22", but we could not catch it (ext.kotlin_version = '1.9.22'). Can you run the "flutter doctor -v" command and share your output with us?

**Comment by naveenpardeep** [comment]
![image](https://github.com/Biscozum/mobkit_calendar/assets/42085829/c04829dd-1029-430a-bc09-c792ed30c518)

**Comment by burakhang** [comment]
We could not see the same error with the versions you specified. If it is suitable for you, can you share your sample project?
